#!/usr/bin/env bash

# Huion Q620M on-screen annotation with Gromit-MPX.
#
# The whole point of this step is one decision: keep the tablet on the
# in-kernel hid-uclogic driver and away from Huion's own user-space driver.
#
# The huiontablet package (installed by hand from a vendor .deb, not by this
# repo) autostarts huionCore, which claims the pen's USB interface through
# uhid and re-emits it as virtual devices. The pen then arrives as
#
#     HUION 256C PEN STYLUS   PROP=0   handlers: mouse5
#
# — an ordinary mouse. Wayland maps only tablet devices to an output, so a
# plain pointer cannot be confined to a screen, and every mapping control in
# the stack silently does nothing: the driver's own screenReflectMod, KDE's
# OutputUuid, MapToWorkspace, and the Drawing Tablet panel. Observed symptom
# was a full-width pen sweep covering roughly the middle third of the middle
# monitor, because huionCore emitted only the middle third of the coordinate
# range it declared, and every layer below faithfully carried that narrowing
# through whatever target it was pointed at. KDE's own Drawing Tablet page
# says as much in a banner: "This device is managed by a user-space driver
# that you installed."
#
# With huionCore out of the way the kernel binds all three USB interfaces and
# exposes the real thing:
#
#     HUION Huion tablet_Q620M Pen   PROP=1   ABS=d000003   (X, Y, PRESSURE,
#                                                            TILT_X, TILT_Y)
#     ...Pad / Touch Strip / Dial / Keyboard
#
# which KWin maps to the primary screen, and which finally gives Gromit
# pressure-varying stroke width.
#
# Nothing here pins the tablet to a particular monitor. KWin's default for an
# opaque tablet is the primary screen, which is where annotation belongs and
# which follows the primary screen if the desk layout changes. A hardcoded
# OutputUuid would survive exactly until the next monitor or cable swap.

set -euo pipefail

step_dir="$(cd "$(dirname "$0")" && pwd)"

echo "----> Keeping the Huion tablet on the kernel driver"

# /etc/xdg/autostart/huiontablet.desktop ships with the vendor package, so it
# cannot be deleted without the next package upgrade putting it back. A
# same-named file in the user's autostart directory shadows it, and Hidden=true
# is the XDG-specified way to say "treat as absent". Reversible by deleting
# this file; the vendor GUI still runs on demand for firmware or pad-key work
# that only its own tool can do.
autostart_dir="$HOME/.config/autostart"
mkdir -p "$autostart_dir"
cat >"$autostart_dir/huiontablet.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=HuionTablet
Exec=/usr/lib/huiontablet/huiontablet.sh
Hidden=true
EOF

# Stop it for the current session too, so the step takes effect without a
# relogin. The unit is generated by systemd's XDG autostart generator, so it
# only exists once the desktop session has started it.
if systemctl --user is-active --quiet app-huiontablet@autostart.service; then
    systemctl --user stop app-huiontablet@autostart.service
    echo "     huionCore stopped — replug the tablet so the kernel claims the pen"
else
    echo "     huionCore not running"
fi

echo "----> Clearing stale tablet mappings"

# Two dead entries accumulate from configuring the tablet while the vendor
# driver owned it. Both name devices that no longer exist, and the first one
# points at the LEFT monitor — harmless now, but it would be a nasty thing to
# rediscover if KDE ever matched it by name again.
drop_libinput_key() {
    kwriteconfig6 --file kcminputrc \
        --group Libinput --group "$1" --group "$2" --group "$3" \
        --key "$4" --delete
}

drop_libinput_key 9580 61165 "HUION 256C PEN STYLUS" OutputArea
drop_libinput_key 9580 61165 "HUION 256C PEN STYLUS" OutputUuid
drop_libinput_key 9580 65535 "Huion Tablet" MapToWorkspace

echo "----> Binding the Q620M pad keys to Gromit-MPX"

# Gromit grabs F9 (toggle) and F8 (undo) with SHIFT variants for clear and
# redo. Under Wayland an XWayland client cannot grab keys globally, so the
# pad keys are rebound in KDE to those same keysyms and KWin delivers them.
#
# Key numbers are libinput button numbers on the Pad device, not the numbers
# printed on the tablet. These three were established by trial; leave the rest
# unbound rather than guessing at the physical layout.
pad_rebind() {
    kwriteconfig6 --file kcminputrc \
        --group ButtonRebinds --group Tablet \
        --group "HUION Huion tablet_Q620M Pad" \
        --key "$1" "Key,$2"
}

pad_rebind 6 "Shift+F9"   # clear the screen
pad_rebind 7 "F9"         # toggle painting
pad_rebind 8 "Meta+Shift+F12"

echo "----> Installing the Gromit-MPX tool configuration"

install -Dm644 "$step_dir/gromit-mpx.cfg" \
    "$HOME/.config/gromit-mpx/gromit-mpx.cfg"

# Gromit reads its config only at startup and offers no reload.
if pgrep -x gromit-mpx >/dev/null; then
    gromit-mpx --quit >/dev/null 2>&1 || true
    echo "     Gromit stopped — restart it to pick up the new tools"
fi

# The package ships no autostart entry, and Gromit is only useful sitting in
# the tray waiting for its hotkey.
cat >"$autostart_dir/net.christianbeier.Gromit-MPX.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=Gromit-MPX
Exec=gromit-mpx
Icon=net.christianbeier.Gromit-MPX
Terminal=false
X-GNOME-Autostart-enabled=true
EOF
